# Generated by Django 6.1 on 2026-09-09 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.timeslot'),
        ),
    ]
