# Generated by Django 6.1 on 2026-09-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('receptionist', 'Receptionist')], default='receptionist', max_length=20),
        ),
        migrations.AddField(
            model_name='staff',
            name='services',
            field=models.ManyToManyField(to='bookings.service'),
        ),
    ]
